---
title: "Media"
output:
  html_document:
    toc: true
    toc_depth: 3
---

While many capstone projects have made substantial and long-lasting contributions on their sponsoring organization, many of those contributions never become public. 
Here, we note a few of the more public contributions. 


## ProPublica project

- Capstone students were acknowledged for their contributions to Sophie Chou and Brenda Medina's article ["Despite Audit, Doctors With Checkered Records Can Still Decide Fate of Green Card Seekers"](https://www.propublica.org/article/despite-audit-doctors-with-checkered-records-can-still-decide-fate-of-green-card-seekers) for ProPublica.  

> "Smith College Statistical and Data Science capstone students provided additional research."

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">So proud of the work that <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> students did in helping to collect data for this <a href="https://twitter.com/propublica?ref_src=twsrc%5Etfw">@propublica</a> story. Thanks for working with us <a href="https://twitter.com/ryanngro?ref_src=twsrc%5Etfw">@ryanngro</a> <a href="https://twitter.com/mpetitchou?ref_src=twsrc%5Etfw">@mpetitchou</a>! Despite Audit, Doctors With Checkered Records Can Still Decide Fate of Green Card Seekers <a href="https://t.co/JJoaHiiozs">https://t.co/JJoaHiiozs</a></p>&mdash; Ben Baumer (@BaumerBen) <a href="https://twitter.com/BaumerBen/status/1224746812424294401?ref_src=twsrc%5Etfw">February 4, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

## OpenElections project

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">This fall we had the great fortune of having data science students from <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> spend a semester working on OpenElections.<br><br>These four young women wrote parsers for tricky electronic PDFs, wrote a paper describing their methods &amp; built a site:<a href="https://t.co/5qN8g0Mji4">https://t.co/5qN8g0Mji4</a></p>&mdash; OpenElections (@openelex) <a href="https://twitter.com/openelex/status/1208400228581302273?ref_src=twsrc%5Etfw">December 21, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Congrats to <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> students Tiffany Xiao <a href="https://twitter.com/_mxwang?ref_src=twsrc%5Etfw">@_mxwang</a> <a href="https://twitter.com/karavan_allen?ref_src=twsrc%5Etfw">@karavan_allen</a> Karen Santamaria on winning 3rd 🏆 in the fall <a href="https://twitter.com/hashtag/USRESP?src=hash&amp;ref_src=twsrc%5Etfw">#USRESP</a> competition!! Project sponsored by <a href="https://twitter.com/openelex?ref_src=twsrc%5Etfw">@openelex</a> <a href="https://twitter.com/derekwillis?ref_src=twsrc%5Etfw">@derekwillis</a> <a href="https://t.co/TOPOODo0Lx">https://t.co/TOPOODo0Lx</a></p>&mdash; Ben Baumer (@BaumerBen) <a href="https://twitter.com/BaumerBen/status/1235363781754138626?ref_src=twsrc%5Etfw">March 5, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Other tweets


<a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @SmithCollegeSDS</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Does your organization use data for good? Want to connect with excellent <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> majors? Consider becoming a SDS capstone sponsor! My DMs are open!<br><br>More information here: <a href="https://t.co/gXXY6VHchs">https://t.co/gXXY6VHchs</a></p>&mdash; Miles Ott 🏳️
⚧️ (@Miles_Ott) <a href="https://twitter.com/Miles_Ott/status/1205568686226116608?ref_src=twsrc%5Etfw">December 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Tfw you present to your client and then hit up <a href="https://twitter.com/momofuku?ref_src=twsrc%5Etfw">@momofuku</a> for lunch. <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> <a href="https://twitter.com/hashtag/smithieslead?src=hash&amp;ref_src=twsrc%5Etfw">#smithieslead</a> <a href="https://t.co/xVhNGdp6PG">pic.twitter.com/xVhNGdp6PG</a></p>&mdash; Ben Baumer (@BaumerBen) <a href="https://twitter.com/BaumerBen/status/993555071916019712?ref_src=twsrc%5Etfw">May 7, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 