---
title: "Projects"
output:
  html_document:
    toc: true
---

## Current projects

We are currently seeking new sponsors for the fall 2020 semester. Please see the [sponsors](sponsors.html) page for information about sponsoring a project, and the [project archive](projects.html#project_archive) for information about past projects.  

## Project archive


```{r, include=FALSE}
library(tidyverse)
```

```{r, eval=FALSE, include=FALSE}
library(googlesheets)
key <- "17nrW5cXHFeoISeNdU_DEYfb_t6i49lUv5Ie_mbIO6Zo"
gs_auth()
g <- gs_key(key)
g <- gs_ls()

# currently not working. Download spreadsheet manually

```

```{r, echo=FALSE, message=FALSE}
archive <- read_csv(here::here("capstone_db.csv"))

archive %>%
    arrange(desc(year), semester, client) %>%
    mutate(Term = paste(stringr::str_to_title(semester), year), 
           Title = ifelse(repo_public, paste0("[", title, "](", repo, ")"), title), 
           Sponsor = ifelse(client_public, paste0("[", client, "](", url, ")"), "[redacted]")) %>%
    select(Term, Sponsor, Title, Students = students) %>%
    knitr::kable(caption = "Previous capstone sponsors")
```
